import { Activity } from './Activity.js';
import { drawActivityBackground, drawInstructionPanel, drawToken } from './activityDraw.js';
export class StoryChoiceActivity extends Activity {
  start(){this.choices=(this.definition.choices??[]).map((c,i)=>({...c,id:c.id??`story-${i}`,x:c.x??620+i*430,y:c.y??690,size:c.size??135,wobble:0}));super.start();}
  update(dt){super.update(dt);for(const c of this.choices)c.wobble=Math.max(0,c.wobble-dt);}
  getHintContext(){const c=this.choices.find(c=>c.correct||c.id===this.definition.correctId)??null;return c?{object:c,target:c,skillIds:this.configuredSkills()}:null;}
  handlePointer(e){if(e.type!=='up')return;const c=this.choices.find(c=>Math.abs(e.x-c.x)<=180&&Math.abs(e.y-c.y)<=150);if(!c)return;const hasCorrect=this.choices.some(x=>x.correct||x.id===this.definition.correctId);const ok=!hasCorrect||c.correct||c.id===this.definition.correctId;if(ok){this.recordResponse(this.configuredSkills(),'success');this.cue('correct');this.complete({detail:c.resultText??this.definition.completeDetail??'Good choice!'});}else{c.wobble=.4;this.recordResponse(this.configuredSkills(),'incorrect');this.cue('incorrect');this.react('encourage',{duration:.8});}}
  render(ctx){drawActivityBackground(ctx,this.definition.theme??'rainbow');ctx.fillStyle='#ffffffcc';ctx.beginPath();ctx.roundRect(480,280,960,220,70);ctx.fill();ctx.fillStyle='#5a3a73';ctx.textAlign='center';ctx.font='800 38px system-ui';ctx.fillText(this.definition.storyText??'What should we do?',960,395);for(const c of this.choices){ctx.fillStyle='#ffffffdd';ctx.beginPath();ctx.roundRect(c.x-180,c.y-150,360,300,55);ctx.fill();drawToken(ctx,c.kind==='thing'?{...c,label:null}:c,{wobble:c.wobble>0?Math.sin(this.t*18)*.1:0});ctx.fillStyle='#5a3a73';ctx.textAlign='center';ctx.font='800 28px system-ui';ctx.fillText(c.label??'',c.x,c.y+120);}drawInstructionPanel(ctx,this.definition.instructionText??(this.definition.storyText?'Pick one!':'Choose what happens next'),this.definition.subtitle??'Tap a picture');}
}
