import { Activity } from './Activity.js';
import { drawActivityBackground, drawInstructionPanel } from './activityDraw.js';

export class TracePathActivity extends Activity {
  start(){this.points=this.definition.points??[{x:520,y:760},{x:760,y:560},{x:1040,y:700},{x:1360,y:430}];this.progress=0;this.active=false;this.trail=[];this.tolerance=this.definition.tolerance??110;super.start();}
  getHintContext(){const p=this.points[Math.min(this.progress,this.points.length-1)];return p?{object:p,target:p,skillIds:this.configuredSkills()}:null;}
  handlePointer(e){if(e.type==='down'){if(Math.hypot(e.x-this.points[0].x,e.y-this.points[0].y)<=this.tolerance*1.4){this.active=true;this.progress=1;this.trail=[{x:e.x,y:e.y}];}}else if(e.type==='move'&&this.active){this.trail.push({x:e.x,y:e.y});const next=this.points[this.progress];if(next&&Math.hypot(e.x-next.x,e.y-next.y)<=this.tolerance){this.progress++;this.recordResponse(this.configuredSkills(),'success');this.cue('drop');if(this.progress>=this.points.length){this.active=false;this.cue('correct');this.complete({detail:this.definition.completeDetail??'Great tracing!'});}}}else if(e.type==='up'||e.type==='cancel'){if(this.active&&this.progress<this.points.length){this.recordResponse(this.configuredSkills(),'incorrect');this.cue('incorrect');}this.active=false;}}
  render(ctx){drawActivityBackground(ctx,this.definition.theme??'meadow');ctx.strokeStyle='#ffffffbb';ctx.lineWidth=42;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();this.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#8b69db';ctx.lineWidth=14;ctx.setLineDash?.([26,24]);ctx.beginPath();this.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash?.([]);if(this.trail.length>1){ctx.strokeStyle='#f7cf4f';ctx.lineWidth=30;ctx.beginPath();this.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}for(let i=0;i<this.points.length;i++){ctx.fillStyle=i<this.progress?'#66bd62':'#fff';ctx.beginPath();ctx.arc(this.points[i].x,this.points[i].y,28,0,Math.PI*2);ctx.fill();}drawInstructionPanel(ctx,this.definition.instructionText??'Trace the path',this.definition.subtitle??'Start at the first dot and follow the line');}
}
